# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 09:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.TextField(default='1')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Publishable', 'Publishable')], max_length=20)),
                ('modified', models.CharField(editable=False, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField()),
                ('revision', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.TextField()),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('salad_schema', models.TextField()),
                ('jsonld_context', models.TextField()),
                ('rdf_definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('mandatory_fields', models.CharField(max_length=100)),
                ('transport_rule', models.TextField()),
                ('masked_fields', models.TextField()),
                ('is_encrypted', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectschemas', to='core.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.TextField(default='1')),
                ('map_revision', models.TextField(default='1')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.Mapping')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField()),
                ('revision', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='projectschema',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectschemas', to='core.Schema'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.Project'),
        ),
        migrations.AddField(
            model_name='entity',
            name='projectschema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.ProjectSchema'),
        ),
        migrations.AddField(
            model_name='entity',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.Response'),
        ),
    ]
