# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 15:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.TextField(default='1')),
                ('map_revision', models.TextField(default='1')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.Mapping')),
            ],
        ),
        migrations.RemoveField(
            model_name='response',
            name='mapping',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='response',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='entity',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.Submission'),
        ),
    ]
