# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.TextField()),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Publishable', 'Publishable')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField()),
                ('revision', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('salad_schema', models.TextField()),
                ('jsonld_context', models.TextField()),
                ('rdf_definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory_fields', models.CharField(max_length=100)),
                ('transport_rule', models.TextField()),
                ('masked_fields', models.TextField()),
                ('is_encrypted', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectschemas', to='core.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField()),
                ('revision', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='response',
        ),
        migrations.RemoveField(
            model_name='mapfunction',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='mapresult',
            name='map_function',
        ),
        migrations.RemoveField(
            model_name='mapresult',
            name='response',
        ),
        migrations.RemoveField(
            model_name='reducefunction',
            name='map_function',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='created_by',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='data',
            new_name='payload',
        ),
        migrations.RemoveField(
            model_name='response',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='response',
            name='survey',
        ),
        migrations.AddField(
            model_name='response',
            name='map_revision',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='revision',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='MapFunction',
        ),
        migrations.DeleteModel(
            name='MapResult',
        ),
        migrations.DeleteModel(
            name='ReduceFunction',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.AddField(
            model_name='projectschema',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectschemas', to='core.Schema'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.Project'),
        ),
        migrations.AddField(
            model_name='entity',
            name='projectschema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.ProjectSchema'),
        ),
        migrations.AddField(
            model_name='entity',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.Response'),
        ),
        migrations.AddField(
            model_name='response',
            name='mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.Mapping'),
        ),
    ]
