# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171101_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
