# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171101_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='type',
            field=models.CharField(default='type', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='revision',
            field=models.TextField(default='1'),
        ),
    ]
