# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171106_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='modified',
            field=models.CharField(default='test', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
