# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 12:23
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokens',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='app_tokens', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('kernel_token', models.CharField(blank=True, max_length=40, null=True)),
                ('odk_token', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'default_related_name': 'app_tokens',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('mapping_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'default_related_name': 'surveys',
            },
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('columns', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='gather.Survey')),
            ],
            options={
                'default_related_name': 'masks',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mask',
            unique_together=set([('survey', 'name')]),
        ),
    ]
