# Generated by Django 2.0.2 on 2018-02-28 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokens',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='app_tokens', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('kernel_token', models.CharField(blank=True, max_length=40, null=True)),
                ('odk_token', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'default_related_name': 'app_tokens',
            },
        ),
    ]
