# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-21 09:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_verbose_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='mapping',
            new_name='mapping_rules',
        ),
        migrations.AddField(
            model_name='contract',
            name='mapping',
            field=models.UUIDField(blank=True, help_text='This ID corresponds to an Aether Kernel mapping ID.', null=True, unique=True, verbose_name='mapping ID'),
        ),

        migrations.AlterField(
            model_name='pipeline',
            name='mappingset',
            field=models.UUIDField(blank=True, help_text='This ID corresponds to an Aether Kernel mapping set ID.', null=True, unique=True, verbose_name='mapping set ID'),
        ),
    ]
