# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 13:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='kernel_refs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, editable=False),
        ),
    ]
