# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-21 09:42
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


def migrate_create_projects(apps, schema_editor):
    Project = apps.get_model('ui', 'Project')
    Pipeline = apps.get_model('ui', 'Pipeline')

    # create default project for all pipelines without any (not published yet)
    default_project = Project.objects.create(name=settings.DEFAULT_PROJECT_NAME, is_default=True)

    for pipeline in Pipeline.objects.all():
        pipeline.project = default_project  # set the default project

        # create project based on pipeline contracts (extract project ID from kernel_refs)
        for contract in pipeline.contracts.all():
            if contract.kernel_refs and contract.kernel_refs.get('project'):
                project_id = contract.kernel_refs.get('project')
                project, created = Project.objects.get_or_create(project_id=project_id)
                if created:
                    project.name = pipeline.name
                    project.save()

                pipeline.project = project
                break  # ASSUMPTION: all contracts are linked to the same project

        pipeline.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_rename_mapping_to_mapping_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('project_id', models.UUIDField(default=uuid.uuid4, help_text='This ID corresponds to an Aether Kernel project ID.', primary_key=True, serialize=False, verbose_name='project ID')),
                ('name', models.TextField(blank=True, default='', null=True, verbose_name='name')),
                ('is_default', models.BooleanField(default=False, editable=False, verbose_name='is the default project?')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['name'],
                'default_related_name': 'projects',
            },
        ),

        migrations.AddField(
            model_name='pipeline',
            name='project',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='ui.Project', verbose_name='project'),
            preserve_default=False,
        ),

        migrations.RunPython(
            code=migrate_create_projects,
            reverse_code=migrations.RunPython.noop,
            # The optional elidable argument determines whether or not the operation
            # will be removed (elided) when squashing migrations.
            elidable=True,
        ),

        migrations.AlterField(
            model_name='pipeline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='ui.Project', verbose_name='project'),
        ),

        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['project', '-modified'], name='ui_pipeline_project_2fab7e_idx'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['-modified'], name='ui_pipeline_modifie_e896fc_idx'),
        ),
    ]
