# Generated by Django 2.1.7 on 2019-03-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0100_initial_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
    ]
