# Generated by Django 2.1.7 on 2019-03-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0101_name_as_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_identity',
            field=models.BooleanField(default=False, verbose_name='is identity?'),
        ),
    ]
