# Generated by Django 2.2.6 on 2019-11-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0102_contract_is_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
