# Generated by Django 3.1.11 on 2021-05-27 12:58

import aether.sdk.drf.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0104_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='entity_types',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='entity types'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='kernel_refs',
            field=models.JSONField(blank=True, editable=False, help_text='These IDs correspond to Aether Kernel artefact IDs.', null=True, verbose_name='Kernel artefact IDs'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='mapping_errors',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='mapping errors'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='mapping_rules',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='mapping rules'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='output',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='output'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='input',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='input JSON'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='schema',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='AVRO schema'),
        ),
    ]
