# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-17 15:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2015, 11, 17, 15, 18, 43, 155500, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
