version: '2.1'

networks:
  # docker network create aether_internal
  internal:
    external:
      # if this isn't explicitly set it inherits from the containing folder name (aether or not)
      name: aether_internal

volumes:
  # docker volume create aether_database_data
  database_data:
    external:
      name: aether_database_data

services:

  # ---------------------------------
  # Database
  # ---------------------------------

  db:
    extends:
      file: ./docker-compose-base.yml
      service: postgres-base
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - internal

  # ---------------------------------
  # Authorization modules
  # ---------------------------------

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: db
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}

      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8090
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8090:8090"
      # - "80:80"
      # - "8001:8001"  # internal only
      # - "8443:8443"  # Once ODK is integrated, we can take these
      # - "8444:8444"
    networks:
      - internal

  keycloak:
    build: ./aether-auth/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: ${KEYCLOAK_PG_PASSWORD}

      KEYCLOAK_USER: ${KEYCLOAK_GLOBAL_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_GLOBAL_PASSWORD}

      PROXY_ADDRESS_FORWARDING: 'true'
      PROXY_PORT_FORWARDING: 'true'
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - internal

  auth:
    image: aether-auth
    build: ./aether-auth
    environment:
      BASE_HOST: http://aether.local:8090
      KEYCLOAK_INTERNAL: http://keycloak:8080
      KONG_INTERNAL: http://kong:8001

      KEYCLOAK_GLOBAL_ADMIN: ${KEYCLOAK_GLOBAL_ADMIN}
      KEYCLOAK_GLOBAL_PASSWORD: ${KEYCLOAK_GLOBAL_PASSWORD}

      APP_NAME: auth
      APP_INTERNAL: http://auth:3012
      APP_PORT: 3012

      JWT_COOKIE: aether-jwt
      REALM_COOKIE: aether-realm
    volumes:
      - ./aether-auth:/code
    depends_on:
      kong:
        condition: service_started
      keycloak:
        condition: service_started
    command: start
    networks:
      - internal

  # ---------------------------------
  # Aether modules
  # ---------------------------------

  kernel:
    extends:
      file: ./docker-compose-base.yml
      service: kernel-base
    environment:
      DEBUG: null
      CSRF_COOKIE_DOMAIN: aether.local
      HOSTNAME: aether.local

      BASE_HOST: http://aether.local
      KEYCLOAK_URL: http://keycloak:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
    command: start
