# ------------------------------------------------------------------------------
# Aether Utilities containers to setup build of python modules
# ------------------------------------------------------------------------------

version: "2.1"

services:

  common:
    build: ./aether-common-module
    environment:
      TESTING: "true"
      # required environment variables
      DJANGO_SECRET_KEY: secret
      DJANGO_STORAGE_BACKEND: filesystem
      PGPASSWORD: secretsecret
      PGUSER: dbuser
      PGHOST: db-test
      PGPORT: "9999"
      DB_NAME: common
      # required by kernel module
      AETHER_KERNEL_URL_TEST: http://kernel-test
      HOSTNAME: 'example.com'
    volumes:
      - ./aether-common-module:/code
    command: build


  client:
    build: ./aether-utils/aether-client
    environment:
      TESTING: "true"
    volumes:
      - ./aether-utils/aether-client:/code
    command: build


  mocker:
    build: ./aether-utils/aether-mock-data
    environment:
      TESTING: "true"
    volumes:
      - ./aether-utils/aether-mock-data:/code
    command: build


  saladbar:
    build: ./aether-utils/aether-saladbar
    environment:
      TESTING: "true"
    volumes:
      - ./aether-utils/aether-saladbar:/code
    command: build
