# Adds Aether Producer
version: "2"
services:

  # ---------------------------------
  # Aether Kafka Producer
  # ---------------------------------

  aether-producer:
    build: aether-producer
    image: aether-producer
    stdin_open: true
    volumes:
     - ./aether-producer:/code
     - ./aether-client:/code/aether-client
    environment:
     - PYTHONUNBUFFERED=1
    links:
      - kafka
      - zookeeper
    networks:
      - internal
    command: start_dev

