# ------------------------------------------------------------------------------
# Config file for only these containers:
#
#  * Aether Kernel
#  * CouchDB Sync Module
# ------------------------------------------------------------------------------

version: "2"

networks:
  internal-sync:
    driver: bridge

services:

  # ---------------------------------
  # Database containers
  # ---------------------------------

  db:
    extends:
      file: docker-compose-base.yml
      service: postgres-base
    networks:
      - internal-sync

  couchdb:
    extends:
      file: docker-compose-base.yml
      service: couchdb-base
    networks:
      - internal-sync

  redis:
    extends:
      file: docker-compose-base.yml
      service: redis-base
    networks:
      - internal-sync


  # ---------------------------------
  # Aether Kernel
  # ---------------------------------

  kernel:
    extends:
      file: docker-compose-base.yml
      service: kernel-base
    depends_on:
      - db
    networks:
      internal-sync:
        aliases:
          - kernel.aether.local


  # ---------------------------------
  # CouchDB Sync module
  # ---------------------------------

  couchdb-sync:
    extends:
      file: docker-compose-base.yml
      service: couchdb-sync-base
    depends_on: &sync-dependencies
      - couchdb
      - db
      - kernel
      - redis
    networks:
      internal-sync:
        aliases:
          - sync.aether.local

  couchdb-sync-rq:
    extends:
      file: docker-compose-base.yml
      service: couchdb-sync-rq-base
    depends_on: *sync-dependencies
    networks:
      - internal-sync


  # ---------------------------------
  # NGINX container
  # ---------------------------------

  nginx:
    extends:
      file: docker-compose-base.yml
      service: nginx-base
    volumes:
      # override config file
      - ./local-setup/nginx.conf.sync.local:/etc/nginx/conf.d/default.conf
    depends_on:
      - kernel
      - couchdb-sync
    networks:
      - internal-sync
