# Adds E and K from the ELK stack
version: "2.1"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    networks:
      - aether

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.4
    ports:
      - "5601:5601"
    environment:
      xpack.security.enabled: "false"
      kibana.index: "aether-demo-2"
    depends_on:
      - elasticsearch
    networks:
      - aether

  es-consumer:
    build: consumer-elasticsearch
    stdin_open: true
    volumes:
     - ./consumer-elasticsearch:/code
    environment:
     - PYTHONUNBUFFERED=1
    links:
      - elasticsearch
    networks:
      - aether
    command: start_dev

networks:
  aether:
    external:
      name: aether_internal
