version: '2.1'

networks:
  # docker network create aether_internal
  internal:
    external:
      # if this isn't explicitly set it inherits from the containing folder name (aether or not)
      name: aether_internal

volumes:
  # docker volume create aether_database_data
  database_data:
    external:
      name: aether_database_data

services:

  # ---------------------------------
  # Database
  # ---------------------------------

  db:
    extends:
      file: ./docker-compose-base.yml
      service: postgres-base
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - internal

  # ---------------------------------
  # Authorization modules
  # ---------------------------------

  kong:
    image: kong:latest
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_CASSANDRA_CONTACT_POINTS: db

      KONG_DATABASE: postgres
      KONG_PG_HOST: db
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}

      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8090
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8090:8090/tcp"
      # - "80:80/tcp"
      # - "8001:8001/tcp"  # internal only
      # - "8443:8443/tcp"  Once ODK is integrated, we can take these
      # - "8444:8444/tcp"
    networks:
      - internal

  keycloak:
    build: ./aether-auth/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: ${KEYCLOAK_PG_PASSWORD}

      KEYCLOAK_USER: ${KEYCLOAK_GLOBAL_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_GLOBAL_PASSWORD}

      PROXY_ADDRESS_FORWARDING: 'true'
      PROXY_PORT_FORWARDING: 'true'
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - internal

  auth:
    build: ./aether-auth
    environment:
      BASE_HOST: aether.local:8090
      KEYCLOAK_GLOBAL_ADMIN: ${KEYCLOAK_GLOBAL_ADMIN}
      KEYCLOAK_GLOBAL_PASSWORD: ${KEYCLOAK_GLOBAL_PASSWORD}
      KEYCLOAK_INTERNAL: keycloak:8080
      KONG_INTERNAL: kong:8001
      APP_NAME: auth
      APP_PORT: 3012
    volumes:
      - ./aether-auth:/code
    depends_on:
      kong:
        condition: service_started
      keycloak:
        condition: service_started
    command: start
    networks:
      - internal

  # ---------------------------------
  # Aether modules
  # ---------------------------------

  kernel:
    extends:
      file: ./docker-compose-base.yml
      service: kernel-base
    environment:
      # DEBUG: null
      APP_INTERNAL: http://kernel:8000
      BASE_HOST: aether.local:8090
      CSRF_COOKIE_DOMAIN: aether.local
      HOSTNAME: aether.local:8090/kernel
      KEYCLOAK_INTERNAL: keycloak:8080
      KONG_INTERNAL: kong:8001
    volumes:
      - ./aether-common-module/aether/common:/code/aether/common
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
