# ------------------------------------------------------------------------------
# Config file for ALL TESTING containers:
#
#  * Aether Kernel
#  * ODK Module
#  * CouchDB Sync Module
#  * Aether UI
#  * Zookeper & Kafka
#  * Aether Kafka Producer
#  * Aether Integration Tests
# ------------------------------------------------------------------------------

version: "2.1"

services:

  # ---------------------------------
  # Database containers
  # ---------------------------------

  db-test:
    extends:
      file: ./docker-compose-test.yml
      service: db-test

  couchdb-test:
    extends:
      file: ./docker-compose-test.yml
      service: couchdb-test

  redis-test:
    extends:
      file: ./docker-compose-test.yml
      service: redis-test


  # ---------------------------------
  # Aether Kernel
  # ---------------------------------

  kernel-test:
    image: aether-kernel:test
    build:
      context: ./aether-kernel
      dockerfile: Dockerfile.test
    extends:
      file: ./docker-compose-test.yml
      service: kernel-test
    volumes:
      # volumes in tests
      - ./tmp/test/kernel/media:/media
      - ./tmp/test/kernel/static:/var/www/static
      - ./tmp/test/kernel/tmp:/tmp
      - ${HOME}/.cache/pip:/.cache/pip
    command: start_travis


  # ---------------------------------
  # Aether Kernel Client
  # ---------------------------------

  client-test:
    image: aether-client:test
    build:
      context: ./aether-utils/aether-client
      dockerfile: Dockerfile.test
    extends:
      file: ./docker-compose-test.yml
      service: client-test
    volumes:
      - ./aether-utils/aether-client:/code
      - ./VERSION:/code/VERSION
      - ${HOME}/.cache/pip:/.cache/pip


  # ---------------------------------
  # ODK module
  # ---------------------------------

  odk-test:
    image: aether-odk:test
    build:
      context: ./aether-odk-module
      dockerfile: Dockerfile.test
    extends:
      file: ./docker-compose-test.yml
      service: odk-test
    volumes:
      # volumes in tests
      - ./tmp/test/odk/media:/media
      - ./tmp/test/odk/static:/var/www/static
      - ${HOME}/.cache/pip/:/.cache/pip


  # ---------------------------------
  # CouchDB Sync module
  # ---------------------------------

  couchdb-sync-test:
    image: aether-couchdb-sync:test
    build:
      context: ./aether-couchdb-sync-module
      dockerfile: Dockerfile.test
    extends:
      file: ./docker-compose-test.yml
      service: couchdb-sync-test
    volumes:
      - ${HOME}/.cache/pip:/.cache/pip


  # ---------------------------------
  # Aether UI
  # ---------------------------------

  ui-test:
    image: aether-ui:test
    build:
      context: ./aether-ui
      dockerfile: Dockerfile.test
    extends:
      file: ./docker-compose-test.yml
      service: ui-test
    volumes:
      - ${HOME}/.cache/pip:/.cache/pip

  ui-assets-test:
    extends:
      file: docker-compose-test.yml
      service: ui-assets-test


  # ---------------------------------
  # Kafka & Zookeeper
  # ---------------------------------

  zookeeper-test:
    extends:
      file: ./docker-compose-base.yml
      service: zookeeper-base

  kafka-test:
    extends:
      file: ./docker-compose-base.yml
      service: kafka-base
    links:
      - zookeeper-test
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-test:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-test:29092
      ADVERTISED_HOST_NAME: kafka-test


  # ---------------------------------
  # Aether Kafka Producer
  # ---------------------------------

  producer-test:
    image: aether-producer:test
    build:
      context: ./aether-producer
      dockerfile: Dockerfile.test
    extends:
      file: ./docker-compose-base.yml
      service: aether-producer-base
    environment:
      # These variables will override the ones indicated in the settings file
      KAFKA_URL: kafka-test:29092
      KERNEL_URL: http://kernel-test:9000
      OFFSET_DB_URL: sqlite:///test-offset.db
      POSTGRES_DBNAME: ${TEST_KERNEL_DB_NAME:-test-kernel}
      POSTGRES_HOST: db-test
      SERVER_PORT: 9005
    ports:
      - "9005:9005"
    links:
      - kafka-test
      - zookeeper-test
    volumes:
      - ${HOME}/.cache/pip:/.cache/pip
    command: start_travis


  # ---------------------------------
  # Aether Integration Tests
  # ---------------------------------

  integration-test:
    image: aether-integration:test
    build:
      context: ./test-aether-integration-module
      dockerfile: Dockerfile.test
    extends:
      file: ./docker-compose-test.yml
      service: integration-test
    volumes:
      - ./test-aether-integration-module:/code
      - ./VERSION:/code/VERSION
      - ${HOME}/.cache/pip:/.cache/pip