# Adds E and K from the ELK stack
version: "2"

services:

    logstash:
        image: logstash
        build: logstash
        depends_on:
            - db
        ports:
            - "9600:9600"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            discovery.type: single-node
            xpack.security.enabled: "false" 
        depends_on:
            - logstash

    kibana:
        image: docker.elastic.co/kibana/kibana:5.6.4
        ports:
            - "5601:5601"
        environment:
            xpack.security.enabled: "false" 
            kibana.index: "aether-demo-2"
        depends_on:
            - elasticsearch
            