# ------------------------------------------------------------------------------
# Aether Client module setup to build wheel
# ------------------------------------------------------------------------------

version: "2.1"

services:

  client:
    build: aether-utils/aether-client
    environment:
      TESTING: "true"
    volumes:
      - ./aether-utils/aether-client:/code
    command: build
  # ---------------------------------
