version: "2.1"

services:

  # ---------------------------------
  # Core
  # ---------------------------------

  kernel:
    extends:
      file: ./docker-compose-base.yml
      service: kernel-base

  odk:
    extends:
      file: ./docker-compose-base.yml
      service: odk-base

  couchdb-sync:
    extends:
      file: ./docker-compose-base.yml
      service: couchdb-sync-base

  ui:
    extends:
      file: ./docker-compose-base.yml
      service: ui-base

  # ---------------------------------
  # Connect
  # ---------------------------------

  producer:
    extends:
      file: ./docker-compose-base.yml
      service: aether-producer-base

  # ---------------------------------
  # Test
  # ---------------------------------

  integration-test:
    extends:
      file: ./docker-compose-test.yml
      service: integration-test
