# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokens',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='app_tokens', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('core_token', models.CharField(blank=True, max_length=40, null=True)),
                ('odk_importer_token', models.CharField(blank=True, max_length=40, null=True)),
                ('couchdb_sync_token', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
