# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gather2.odk.api.xform_utils


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ('odk', '0001_initial'),
        ('odk', '0002_auto_20170213_1340'),
        ('odk', '0003_auto_20170226_1356'),
        ('odk', '0002_auto_20170227_1201'),
        ('odk', '0002_auto_20170129_1945'),
        ('odk', '0004_merge_20170316_1101'),
        ('odk', '0005_remove_xform_form_id'),
        ('odk', '0006_xform_form_id'),
        ('odk', '0007_xform_title'),
        ('odk', '0008_xform_surveyors'),
        ('odk', '0009_core_survey'),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('surveyors', models.ManyToManyField(blank=True, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', editable=False)),
                ('form_id', models.TextField(default='', editable=False)),
                ('xml_data', models.TextField(blank=True, validators=[gather2.odk.api.xform_utils.validate_xmldict])),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xforms', to='odk.Survey')),
                ('surveyors', models.ManyToManyField(blank=True, related_name='xforms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
