# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 21:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(default='', editable=False, max_length=64)),
                ('xml_data', models.TextField()),
                ('description', models.TextField(default='', null=True, blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gather_core_url', models.URLField(default='')),
            ],
        ),
    ]
