# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gather2.odk.api.xform_utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('mapping_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('surveyors', models.ManyToManyField(blank=True, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', editable=False)),
                ('form_id', models.TextField(default='', editable=False)),
                ('xml_data', models.TextField(blank=True, validators=[gather2.odk.api.xform_utils.validate_xmldict])),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xforms', to='odk.Survey')),
                ('surveyors', models.ManyToManyField(blank=True, related_name='xforms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
