# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odk', '0001_initial_squashed__0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('mapping_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('surveyors', models.ManyToManyField(blank=True, related_name='mappings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='survey',
            name='surveyors',
        ),
        migrations.RemoveField(
            model_name='xform',
            name='survey',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.AddField(
            model_name='xform',
            name='mapping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='xforms', to='odk.Mapping'),
            preserve_default=False,
        ),
    ]
