# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0002_auto_20170129_1945'),
        ('odk', '0002_auto_20170227_1201'),
        ('odk', '0003_auto_20170226_1356'),
    ]

    operations = [
    ]
