# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0005_remove_xform_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='xform',
            name='form_id',
            field=models.TextField(default='', editable=False),
        ),
    ]
