# ------------------------------------------------------------------------------
# Aether Utilities containers to setup build of python modules
# ------------------------------------------------------------------------------

version: "2.1"

services:

  client:
    build: ./aether-client
    environment:
      TESTING: "true"
    volumes:
      - ./aether-client:/code
      - ../tmp/VERSION:/code/VERSION
    command: build
