# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0001_initial'),
    ]

    operations = [
        # to avoid confusion with Kernel data model rename "Survey" to its equivalent there "Mapping"

        migrations.RenameField(
            model_name='xform',
            old_name='survey',
            new_name='mapping',
        ),

        migrations.RenameModel(
            old_name='Survey',
            new_name='Mapping',
        ),

        migrations.AlterField(
            model_name='mapping',
            name='surveyors',
            field=models.ManyToManyField(
                blank=True,
                related_name='mappings',
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        migrations.AlterField(
            model_name='xform',
            name='mapping',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='xforms',
                to='odk.Mapping',
            )
        ),
    ]
