# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 14:16
from __future__ import unicode_literals

from hashlib import md5
import aether.odk.api.models
from django.db import migrations, models
import django.db.models.deletion


def apply_default_values(apps, schema_editor):
    xform_model = apps.get_model('odk', 'xform')
    for xform in xform_model.objects.all():
        # updates md5sum
        xform.md5sum = md5(xform.xml_data.encode('utf8')).hexdigest()
        xform.save()


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0002_rename_survey_to_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('media_file', models.FileField(upload_to=aether.odk.api.models.__media_path__)),
                ('md5sum', models.CharField(editable=False, max_length=36)),
            ],
            options={
                'ordering': ['xform', 'name'],
                'default_related_name': 'media_files',
            },
        ),
        migrations.AlterModelOptions(
            name='mapping',
            options={'ordering': ['name']},
        ),

        migrations.AlterModelOptions(
            name='xform',
            options={'ordering': ['title', 'form_id']},
        ),
        migrations.AddField(
            model_name='xform',
            name='md5sum',
            field=models.CharField(editable=False, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='xform',
            name='version',
            field=models.TextField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='xform',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='media_files',
                to='odk.XForm',
            ),
        ),

        # load default values
        migrations.RunPython(
            code=apply_default_values,
            reverse_code=migrations.RunPython.noop,
            # The optional elidable argument determines whether or not the operation
            # will be removed (elided) when squashing migrations.
            elidable=True,
        ),
    ]
