# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 09:09
from __future__ import unicode_literals

import aether.odk.api.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0005_rename_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['xform', 'name'], 'verbose_name': 'media file', 'verbose_name_plural': 'media files'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='xform',
            options={'ordering': ['title', 'form_id'], 'verbose_name': 'xform', 'verbose_name_plural': 'xforms'},
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='md5sum',
            field=models.CharField(editable=False, max_length=36, verbose_name='md5sum'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='media_file',
            field=models.FileField(upload_to=aether.odk.api.models.__media_path__, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='name',
            field=models.TextField(blank=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='xform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='odk.XForm', verbose_name='xForm'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(blank=True, default='', null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='This ID corresponds to an Aether Kernel project ID.', primary_key=True, serialize=False, verbose_name='project ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='surveyors',
            field=models.ManyToManyField(blank=True, help_text='If you do not specify any surveyors, EVERYONE will be able to access this project xForms.', related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='surveyors'),
        ),
        migrations.AlterField(
            model_name='xform',
            name='avro_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True, verbose_name='AVRO schema'),
        ),
        migrations.AlterField(
            model_name='xform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='xform',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='xForm description'),
        ),
        migrations.AlterField(
            model_name='xform',
            name='form_id',
            field=models.TextField(default='', editable=False, verbose_name='xForm ID'),
        ),
        migrations.AlterField(
            model_name='xform',
            name='kernel_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='This ID is used to create Aether Kernel artefacts (schema, project schema and mapping).', verbose_name='Aether Kernel ID'),
        ),
        migrations.AlterField(
            model_name='xform',
            name='md5sum',
            field=models.CharField(default='', editable=False, max_length=36, verbose_name='xForm md5sum'),
        ),
        migrations.AlterField(
            model_name='xform',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xforms', to='odk.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='xform',
            name='surveyors',
            field=models.ManyToManyField(blank=True, help_text='If you do not specify any surveyors, EVERYONE will be able to access this xForm.', related_name='xforms', to=settings.AUTH_USER_MODEL, verbose_name='surveyors'),
        ),
        migrations.AlterField(
            model_name='xform',
            name='title',
            field=models.TextField(default='', editable=False, verbose_name='xForm title'),
        ),
        migrations.AlterField(
            model_name='xform',
            name='version',
            field=models.TextField(blank=True, default='0', verbose_name='xForm version'),
        ),
        migrations.AlterField(
            model_name='xform',
            name='xml_data',
            field=models.TextField(blank=True, help_text='This XML must conform the ODK XForms specification. http://opendatakit.github.io/xforms-spec/', validators=[aether.odk.api.models.__validate_xml_data__], verbose_name='XML definition'),
        ),
    ]
