# Generated by Django 2.1.7 on 2019-03-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0007_xform_modified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'default_related_name': 'media_files', 'ordering': ['xform', 'name'], 'verbose_name': 'media file', 'verbose_name_plural': 'media files'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'default_related_name': 'projects', 'ordering': ['name'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='xform',
            options={'default_related_name': 'xforms', 'ordering': ['title', 'form_id', 'version'], 'verbose_name': 'xform', 'verbose_name_plural': 'xforms'},
        ),
    ]
