# Generated by Django 2.1.7 on 2019-03-11 12:07

import aether.odk.api.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid

#
# https://docs.djangoproject.com/en/2.2/topics/migrations/
#
# Once you’ve squashed your migration, you should then commit it alongside
# the migrations it replaces and distribute this change to all running
# instances of your application, making sure that they run migrate
# to store the change in their database.
#
# You must then transition the squashed migration to a normal migration by:
#
# - Deleting all the migration files it replaces.
# - Updating all migrations that depend on the deleted migrations
#   to depend on the squashed migration instead.
# - Removing the replaces attribute in the Migration class of the
#   squashed migration (this is how Django tells that it is a squashed migration).
#

if settings.MULTITENANCY:
    run_before_multitenancy = [
        ('multitenancy', '0001_initial'),
    ]
else:
    run_before_multitenancy = []


class Migration(migrations.Migration):

    initial = True

    run_before = run_before_multitenancy

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    replaces = [
        ('odk', '0001_initial'),
        ('odk', '0002_rename_survey_to_mapping'),
        ('odk', '0003_media_files'),
        ('odk', '0004_xform_avro_schema'),
        ('odk', '0005_rename_models'),
        ('odk', '0006_verbose_name'),
        ('odk', '0007_xform_modified_at'),
        ('odk', '0008_alter_meta_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, help_text='This ID corresponds to an Aether Kernel project ID.', primary_key=True, serialize=False, verbose_name='project ID')),
                ('name', models.TextField(blank=True, default='', null=True, verbose_name='name')),
                ('surveyors', models.ManyToManyField(blank=True, help_text='If you do not specify any surveyors, EVERYONE will be able to access this project xForms.', related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='surveyors')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['name'],
                'default_related_name': 'projects',
            },
        ),

        migrations.CreateModel(
            name='XForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified at')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='xForm description')),
                ('xml_data', models.TextField(blank=True, help_text='This XML must conform the ODK XForms specification. http://opendatakit.github.io/xforms-spec/', validators=[aether.odk.api.models.__validate_xml_data__], verbose_name='XML definition')),
                ('title', models.TextField(default='', editable=False, verbose_name='xForm title')),
                ('form_id', models.TextField(default='', editable=False, verbose_name='xForm ID')),
                ('version', models.TextField(blank=True, default='0', verbose_name='xForm version')),
                ('md5sum', models.CharField(default='', editable=False, max_length=36, verbose_name='xForm md5sum')),
                ('avro_schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True, verbose_name='AVRO schema')),
                ('kernel_id', models.UUIDField(default=uuid.uuid4, help_text='This ID is used to create Aether Kernel artefacts (schema, project schema and mapping).', verbose_name='Aether Kernel ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xforms', to='odk.Project', verbose_name='project')),
                ('surveyors', models.ManyToManyField(blank=True, help_text='If you do not specify any surveyors, EVERYONE will be able to access this xForm.', related_name='xforms', to=settings.AUTH_USER_MODEL, verbose_name='surveyors')),
            ],
            options={
                'verbose_name': 'xform',
                'verbose_name_plural': 'xforms',
                'ordering': ['title', 'form_id', 'version'],
                'default_related_name': 'xforms',
            },
        ),

        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='name')),
                ('media_file', models.FileField(upload_to=aether.odk.api.models.__media_path__, verbose_name='file')),
                ('md5sum', models.CharField(editable=False, max_length=36, verbose_name='md5sum')),
                ('xform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='odk.XForm', verbose_name='xForm'))
            ],
            options={
                'verbose_name': 'media file',
                'verbose_name_plural': 'media files',
                'ordering': ['xform', 'name'],
                'default_related_name': 'media_files',
            },
        ),
    ]
