# Generated by Django 2.2.7 on 2019-11-26 12:48

import aether.odk.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0103_xform_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='media_file',
            field=models.FileField(max_length=500, upload_to=aether.odk.api.models.__media_path__, verbose_name='file'),
        ),
    ]
