# Generated by Django 3.1 on 2020-08-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0104_mediafile_file_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xform',
            name='avro_schema',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='AVRO schema'),
        ),
    ]
