version: 2.1

jobs:
  machine: true

  # Running core tests
  test-core:
    environment:
      TEST_MODE: core
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Aether CORE tests (Kernel, Client)
          command: ./scripts/test_travis.sh $TEST_MODE
      - run:
          name: Upload Failed Tests
          command: ./scripts/test_travis_failure.sh $TEST_MODE
          when: on_fail

  # Running module tests
  test-modules:
    environment:
      TEST_MODE: modules
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Aether modules tests (ODK and CouchDB-Sync)
          command: ./scripts/test_travis.sh $TEST_MODE
      - run:
          name: Upload Failed Tests
          command: ./scripts/test_travis_failure.sh $TEST_MODE
          when: on_fail

  # running UI tests
  test-ui:
    environment:
      TEST_MODE: ui
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Aether UI tests (UI Module)
          command: ./scripts/test_travis.sh $TEST_MODE
      - run:
          name: Upload Failed Tests
          command: ./scripts/test_travis_failure.sh $TEST_MODE
          when: on_fail

  # runing integration tests
  test-integration:
    environment:
      TEST_MODE: integration
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Aether UI tests (UI Module)
          command: ./scripts/test_travis.sh $TEST_MODE
      - run:
          name: Upload Failed Tests
          command: ./scripts/test_travis_failure.sh $TEST_MODE
          when: on_fail

#  # deploy if tests successful
#  deploy:
#    working_directory: ~/aether
#    executor: python-371
#    steps:
#      - checkout
#      - run:
#          name: Aether release
#          command: ./scripts/release.sh


workflows:
  version: 2
  build_and_test:
    jobs:
      - test-core
      - test-modules
      - test-ui
      - test-integration
#      - deploy
