version: 2.1

orbs:
  docker: circleci/docker@0.5.13

commands:
  test-container:
    description: Run container tests
    parameters:
      container:
        type: string
        default: kernel
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./.circleci/test_ci.sh << parameters.container >>
      - run:
          name: Failed tests
          command: ./.circleci/test_ci_failure.sh << parameters.container >>
          when: on_fail

jobs:

  # Running core tests
  test-core:
    executor: docker/machine
    environment:
      TEST_MODE: core
    steps:
      - test-container:
          container: $TEST_MODE

  # Running module tests
  test-modules:
    executor: docker/machine
    environment:
      TEST_MODE: modules
    steps:
      - test-container:
          container: $TEST_MODE

  # Running UI tests
  test-ui:
    executor: docker/machine
    environment:
      TEST_MODE: ui
    steps:
      - test-container:
          container: $TEST_MODE

  # Runing integration tests
  test-integration:
    executor: docker/machine
    environment:
      TEST_MODE: integration
    steps:
      - test-container:
          container: $TEST_MODE

  release:
    executor: docker/machine
    steps:
      - checkout
      - run:
          name: Push images to Docker Hub
          command: ./.circleci/release.sh

  deploy:
    executor: docker/machine
    steps:
      - checkout
      - run:
          name: Push images to Google Cloud
          command: ./.circleci/deploy.sh

workflows:
  version: 2
  test-release-and-deploy:
    jobs:
      - test-core
      - test-modules
      - test-ui
      - test-integration

      - release:
          # if tests successful
          requires:
            - test-core
            - test-modules
            - test-ui
            - test-integration
          filters:
            # release only in:
            #  branch   develop
            #  branch   release-#.#
            #  tag      #.#.#
            tags:
              only: /^[0-9]+(\.[0-9]+){2}$/
            branches:
              only:
                - develop
                - /^release\-[0-9]+\.[0-9]+$/

      - deploy:
          requires:
            - release
