# Generated by Django 2.2.7 on 2019-11-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='digestcounter',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='digestpartial',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='digestcounter',
            constraint=models.UniqueConstraint(fields=('server_nonce', 'client_nonce'), name='unique_digest_counter'),
        ),
        migrations.AddConstraint(
            model_name='digestpartial',
            constraint=models.UniqueConstraint(fields=('user', 'username'), name='unique_digest_partial'),
        ),
    ]
