# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField(unique=True)),
                ('last_synced_date', models.DateTimeField(blank=True, null=True)),
                ('last_synced_seq', models.TextField(blank=True, null=True, default='0')),
                ('last_synced_log_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
