# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_devicedb_mobileuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('kernel_id', models.UUIDField()),
            ],
            options={
                'ordering': ['name'],
                'default_related_name': 'schemas',
            },
        ),
        migrations.AlterModelOptions(
            name='devicedb',
            options={'ordering': ['-last_synced_date']},
        ),
        migrations.AlterModelOptions(
            name='mobileuser',
            options={'ordering': ['email']},
        ),
    ]
