# Generated by Django 2.1.7 on 2019-03-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_project_artefacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicedb',
            options={'default_related_name': 'devices', 'ordering': ['-last_synced_date'], 'verbose_name': 'device', 'verbose_name_plural': 'devices'},
        ),
        migrations.AlterModelOptions(
            name='mobileuser',
            options={'default_related_name': 'mobileusers', 'ordering': ['email'], 'verbose_name': 'mobile user', 'verbose_name_plural': 'mobile users'},
        ),
        migrations.AlterModelOptions(
            name='schema',
            options={'default_related_name': 'schemas', 'ordering': ['name'], 'verbose_name': 'schema', 'verbose_name_plural': 'schemas'},
        ),
    ]
