# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 11:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [
        ('sync', '0001_initial'),
        ('sync', '0002_devicedb_mobileuser'),
        ('sync', '0003_schema'),
        ('sync', '0004_project_artefacts'),
    ]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField(unique=True)),
                ('last_synced_date', models.DateTimeField(null=True)),
                ('last_synced_seq', models.TextField(default='0', null=True)),
                ('last_synced_log_message', models.TextField(null=True)),
            ],
            options={
                'default_related_name': 'devices',
                'ordering': ['-last_synced_date'],
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
            },
        ),
        migrations.CreateModel(
            name='MobileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
            ],
            options={
                'default_related_name': 'mobileusers',
                'ordering': ['email'],
                'verbose_name': 'mobile user',
                'verbose_name_plural': 'mobile users',
            },
        ),
        migrations.AddField(
            model_name='devicedb',
            name='mobileuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sync.MobileUser'),
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, unique=True, verbose_name='name')),
                ('kernel_id', models.UUIDField(default=uuid.uuid4, help_text='This ID corresponds to an Aether Kernel Artefact ID.', verbose_name='Kernel ID')),
                ('avro_schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='AVRO schema')),
            ],
            options={
                'ordering': ['name'],
                'default_related_name': 'schemas',
                'verbose_name': 'schema',
                'verbose_name_plural': 'schemas',
            },
        ),
        migrations.AlterField(
            model_name='devicedb',
            name='device_id',
            field=models.TextField(unique=True, verbose_name='device ID'),
        ),
        migrations.AlterField(
            model_name='devicedb',
            name='last_synced_date',
            field=models.DateTimeField(null=True, verbose_name='Last synced: date'),
        ),
        migrations.AlterField(
            model_name='devicedb',
            name='last_synced_log_message',
            field=models.TextField(null=True, verbose_name='Last synced: log message'),
        ),
        migrations.AlterField(
            model_name='devicedb',
            name='last_synced_seq',
            field=models.TextField(default='0', null=True, verbose_name='Last synced: sequence'),
        ),
        migrations.AlterField(
            model_name='devicedb',
            name='mobileuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sync.MobileUser', verbose_name='mobile user'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, help_text='This ID corresponds to an Aether Kernel project ID.', primary_key=True, serialize=False, verbose_name='project ID')),
                ('name', models.TextField(blank=True, default='', null=True, verbose_name='name')),
            ],
            options={
                'default_related_name': 'projects',
                'ordering': ['name'],
                'verbose_name_plural': 'projects',
                'verbose_name': 'project',
            },
        ),
        migrations.AddField(
            model_name='schema',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='sync.Project', verbose_name='project'),
        ),
    ]
