# Generated by Django 2.1.7 on 2019-03-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('sync', '0100_initial_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='mobileusers', to='auth.Group', verbose_name='groups'),
        ),
    ]
