# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171031_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='name',
            field=models.CharField(db_index=True, default='sample name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectschema',
            name='name',
            field=models.CharField(db_index=True, default='sample name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schema',
            name='name',
            field=models.CharField(db_index=True, default='sample name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
