# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171102_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
