FROM python:3.6-slim-jessie

################################################################################
## setup container
################################################################################

COPY ./conf/docker/* /tmp/
RUN /tmp/setup.sh

################################################################################
## install app
## copy files one by one and split commands to use docker cache
################################################################################

WORKDIR /code
COPY ./ /code

################################################################################
## copy application version and create git revision
################################################################################

ARG VERSION
RUN echo $VERSION > VERSION
ARG GIT_REVISION
RUN echo $GIT_REVISION > REVISION

################################################################################
## last setup steps
################################################################################

# create user to run container (avoid root user)
# add user with UID of travis' so PIP cache can be written to
RUN useradd -u 2000 -ms /bin/false -g root -G sudo -p travis travis
RUN chown -R travis: /code

ENTRYPOINT ["/code/entrypoint.sh"]
