---
host: "kong:8001"
apis:
  - name: "kernel"
    ensure: "present"
    attributes:
      upstream_url: "http://kernel.aether.local:8000"
      hosts:
        - "PROJECT_API_URL"
      uris:
        - "/aether/v1"
      preserve_host: true
  
  - name: "kernel-home"
    ensure: "present"
    attributes:
      upstream_url: "http://kernel.aether.local:8000"
      hosts:
        - "PROJECT_API_URL"
      preserve_host: true

  - name: "kernel-static"
    ensure: "present"
    attributes:
      upstream_url: "http://kernel.aether.local:8000"
      hosts:
        - "PROJECT_API_URL"
      uris:
        - "/aether/v1/static"
      preserve_host: true
      strip_uri: false

  - name: "kernel-accounts"
    ensure: "present"
    attributes:
      upstream_url: "http://kernel.aether.local:8000"
      hosts:
        - "PROJECT_API_URL"
      uris:
        - "/aether/v1/accounts"
      preserve_host: true
      strip_uri: false

  - name: "odk"
    ensure: "present"
    attributes:
      upstream_url: "https://odk.aether.local:8443"
      uris:
        - "/odk/v1"

  - name: "couch-sync"
    ensure: "present"
    attributes:
      upstream_url: "http://sync.aether.local:8666"
      uris:
        - "/sync/v1"

plugins:
  - name: key-auth
    ensure: "present"
    attributes:
      config:
        key_names:
          - apikey
        hide_credentials: true

consumers:
  - username: KONG_CONSUMER
    credentials:
      - name: key-auth
        attributes:
          key: KONG_APIKEY
