---
host: "kong:8001"
apis:
  - name: "kernel-external"
    ensure: "present"
    attributes:
      upstream_url: "http://kernel:8000"
      hosts:
        - "PROJECT_API_URL"
      uris:
        - "/aether/v1/ext"
      preserve_host: true
    plugins:
      - name: oauth2
        attributes:
          config:
            scopes:
              - "email,phone"
            mandatory_scope: false
            token_expiration: 86400
            enable_authorization_code: true
            enable_password_grant: true
            hide_credentials: false
            provision_key: KONG_OAUTH2_PROVISION_KEY
  
  - name: "kernel-internal"
    ensure: "present"
    attributes:
      upstream_url: "http://kernel:8000"
      hosts:
        - "PROJECT_API_URL"
      uris:
        - "/aether/v1"
      preserve_host: true
    plugins:        
    - name: key-auth
      ensure: "present"
      attributes:
        config:
          key_names:
            - apikey
          hide_credentials: true
  
  - name: "Kong-pass-oauth2"
    ensure: "present"
    attributes:
      upstream_url: "http://kernel:8000"
      uris:
        - "/token"
      preserve_host: true
      strip_uri: false
    plugins:        
    - name: key-auth
      ensure: "present"
      attributes:
        config:
          key_names:
            - apikey
          hide_credentials: true

  - name: "kernel-static"
    ensure: "present"
    attributes:
      upstream_url: "http://kernel:8000/static"
      hosts:
        - "PROJECT_API_URL"
      uris:
        - "/static"
      preserve_host: true

  - name: "kernel-accounts"
    ensure: "present"
    attributes:
      upstream_url: "http://kernel:8000"
      hosts:
        - "PROJECT_API_URL"
      uris:
        - "/accounts"
      preserve_host: true
      strip_uri: false
  
  - name: "kernel-token"
    ensure: "present"
    attributes:
      upstream_url: "http://kernel:8000/accounts/token"
      hosts:
        - "PROJECT_API_URL"
      uris:
        - "/aether/v1/accounts/token"
      preserve_host: true

  - name: "odk"
    ensure: "present"
    attributes:
      upstream_url: "https://odk:8443"
      uris:
        - "/odk/v1"
    plugins:        
    - name: key-auth
      ensure: "present"
      attributes:
        config:
          key_names:
            - apikey
          hide_credentials: true

  - name: "couch-sync"
    ensure: "present"
    attributes:
      upstream_url: "http://sync:8666"
      uris:
        - "/sync/v1"

consumers:
  - username: KONG_CONSUMER
    credentials:
      - name: key-auth
        attributes:
          key: KONG_APIKEY
      - name: oauth2
        attributes:
          name: "Aux"
          redirect_uri: "http://api.aether.local/aux/v1"
          client_id: KONG_CONSUMER

  - username: anonymous_user
    credentials:
      - name: oauth2
        attributes:
          name: "Aux"
          redirect_uri: "http://api.aether.local/aux/v1"
          client_id: "anonymous_user"
