# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 10:40
from __future__ import unicode_literals

import aether.kernel.api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('attachment_file', models.FileField(upload_to=aether.kernel.api.models.__attachment_path__)),
                ('md5sum', models.CharField(blank=True, max_length=36)),
                ('submission_revision', models.TextField()),
            ],
            options={
                'ordering': ['submission__id', 'name'],
                'default_related_name': 'attachments',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('revision', models.TextField(default='1')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Publishable', 'Publishable')], max_length=20)),
                ('modified', models.CharField(editable=False, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['project__id', '-modified'],
                'default_related_name': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('revision', models.TextField(default='1')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_read_only', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-modified'],
                'default_related_name': 'mappings',
            },
        ),
        migrations.CreateModel(
            name='MappingSet',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('revision', models.TextField(default='1')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('input', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['project__id', '-modified'],
                'default_related_name': 'mappingsets',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('revision', models.TextField(default='1')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('salad_schema', models.TextField(blank=True, null=True)),
                ('jsonld_context', models.TextField(blank=True, null=True)),
                ('rdf_definition', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-modified'],
                'default_related_name': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectSchema',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('mandatory_fields', models.TextField(blank=True, null=True)),
                ('transport_rule', models.TextField(blank=True, null=True)),
                ('masked_fields', models.TextField(blank=True, null=True)),
                ('is_encrypted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['project__id', '-modified'],
                'default_related_name': 'projectschemas',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('revision', models.TextField(default='1')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ['-modified'],
                'default_related_name': 'schemas',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('revision', models.TextField(default='1')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('mappingset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kernel.MappingSet')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kernel.Project')),
            ],
            options={
                'ordering': ['project__id', '-modified'],
                'default_related_name': 'submissions',
            },
        ),
        migrations.AddIndex(
            model_name='schema',
            index=models.Index(fields=['-modified'], name='kernel_sche_modifie_fc1ee1_idx'),
        ),
        migrations.AddField(
            model_name='projectschema',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectschemas', to='kernel.Project'),
        ),
        migrations.AddField(
            model_name='projectschema',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectschemas', to='kernel.Schema'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-modified'], name='kernel_proj_modifie_02889d_idx'),
        ),
        migrations.AddField(
            model_name='mappingset',
            name='mappings',
            field=models.ManyToManyField(blank=True, related_name='mappingsets', to='kernel.Mapping'),
        ),
        migrations.AddField(
            model_name='mappingset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappingsets', to='kernel.Project'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['-modified'], name='kernel_mapp_modifie_8c7640_idx'),
        ),
        migrations.AddField(
            model_name='entity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.Project'),
        ),
        migrations.AddField(
            model_name='entity',
            name='projectschema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.ProjectSchema'),
        ),
        migrations.AddField(
            model_name='entity',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.Submission'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='kernel.Submission'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['project', '-modified'], name='kernel_subm_project_3c72d6_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-modified'], name='kernel_subm_modifie_a4d81e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectschema',
            index=models.Index(fields=['project', '-modified'], name='kernel_proj_project_2dfa87_idx'),
        ),
        migrations.AddIndex(
            model_name='projectschema',
            index=models.Index(fields=['-modified'], name='kernel_proj_modifie_3ecab4_idx'),
        ),
        migrations.AddIndex(
            model_name='mappingset',
            index=models.Index(fields=['project', '-modified'], name='kernel_mapp_project_73242f_idx'),
        ),
        migrations.AddIndex(
            model_name='mappingset',
            index=models.Index(fields=['-modified'], name='kernel_mapp_modifie_46a12a_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['project', '-modified'], name='kernel_enti_project_5d5f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['-modified'], name='kernel_enti_modifie_c49ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['submission', 'name'], name='kernel_atta_submiss_58224b_idx'),
        ),
    ]
