# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='project',
            field=models.ForeignKey(default='3e7701a7-8729-4fcf-be0c-42fbc6090b75', on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='kernel.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='schema',
            name='revision',
            field=models.TextField(default='1'),
        ),
        migrations.AlterUniqueTogether(
            name='schema',
            unique_together=set([('name', 'project')]),
        ),
    ]
