# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0003_submission_mapping_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kernel.Mapping'),
        ),
    ]
