# Generated by Django 2.0.1 on 2018-02-01 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0006_auto_20180122_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='revision',
            field=models.TextField(editable=False),
        ),
    ]
