# Generated by Django 2.0.1 on 2018-02-05 13:52

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0007_auto_20180201_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='attachment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachment',
            name='revision',
            field=models.TextField(default='1', editable=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='entity',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mapping',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='mapping',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectschema',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='projectschema',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectschema',
            name='revision',
            field=models.TextField(default='1', editable=False),
        ),
        migrations.AddField(
            model_name='schema',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='schema',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='revision',
            field=models.TextField(default='1', editable=False),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='revision',
            field=models.TextField(default='1', editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='revision',
            field=models.TextField(default='1', editable=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='revision',
            field=models.TextField(default='1', editable=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='revision',
            field=models.TextField(default='1', editable=False),
        ),
    ]
