# Generated by Django 2.0.1 on 2018-02-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0007_auto_20180208_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
