# Generated by Django 2.0.1 on 2018-02-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0008_auto_20180205_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='revision',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='revision',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='revision',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='revision',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='revision',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='revision',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='revision',
            field=models.TextField(editable=False),
        ),
    ]
