# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 18:26
from __future__ import unicode_literals

import aether.kernel.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0009_auto_20180206_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_file',
            field=models.FileField(max_length=500, upload_to=aether.kernel.api.models.__attachment_path__),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
