# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0009_auto_20180220_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ('modified',), 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='mapping',
            options={'ordering': ('modified',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('modified',)},
        ),
        migrations.AlterModelOptions(
            name='projectschema',
            options={'ordering': ('modified',)},
        ),
        migrations.AlterModelOptions(
            name='schema',
            options={'ordering': ('modified',)},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('modified',)},
        ),
    ]
