# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0013_auto_20180530_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='date',
        ),
    ]
