# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0014_remove_submission_date'),
    ]

    operations = [

        migrations.AddField(
            model_name='entity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.Project'),
        ),
        migrations.AddField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kernel.Project'),
        ),

        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['submission__id', 'name']},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['project__id', '-modified'], 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='mapping',
            options={'ordering': ['project__id', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='projectschema',
            options={'ordering': ['project__id', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='schema',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['project__id', '-modified']},
        ),

        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['submission', 'name'], name='kernel_atta_submiss_58224b_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['project', '-modified'], name='kernel_enti_project_5d5f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['-modified'], name='kernel_enti_modifie_c49ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['project', '-modified'], name='kernel_mapp_project_0cb3fd_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['-modified'], name='kernel_mapp_modifie_8c7640_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-modified'], name='kernel_proj_modifie_02889d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectschema',
            index=models.Index(fields=['project', '-modified'], name='kernel_proj_project_2dfa87_idx'),
        ),
        migrations.AddIndex(
            model_name='projectschema',
            index=models.Index(fields=['-modified'], name='kernel_proj_modifie_3ecab4_idx'),
        ),
        migrations.AddIndex(
            model_name='schema',
            index=models.Index(fields=['-modified'], name='kernel_sche_modifie_fc1ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['project', '-modified'], name='kernel_subm_project_3c72d6_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-modified'], name='kernel_subm_modifie_a4d81e_idx'),
        ),

        # set "project" in SUBMISSION and ENTITY instances
        migrations.RunSQL(
            sql='''
            UPDATE kernel_submission S
               SET project_id = M.project_id
              FROM kernel_mapping M
             WHERE S.mapping_id = M.id
            ;

            UPDATE kernel_entity E
               SET project_id = S.project_id
              FROM kernel_submission S
             WHERE E.submission_id = S.id
            ;

            UPDATE kernel_entity E
               SET project_id = PS.project_id
              FROM kernel_projectschema PS
             WHERE E.projectschema_id = PS.id
               AND E.project_id IS NULL
            ;
            ''',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
