# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 12:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0015_auto_20180725_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingSet',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('revision', models.TextField(default='1')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('mappings', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ['project__id', '-modified'],
                'default_related_name': 'mappingsets',
            },
        ),
        migrations.CreateModel(
            name='MappingSetMapping',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['mappingset__id', '-modified'],
                'default_related_name': 'mappingssetmappings',
            },
        ),
        migrations.AlterModelOptions(
            name='mapping',
            options={'ordering': ['-modified']},
        ),
        migrations.RemoveIndex(
            model_name='mapping',
            name='kernel_mapp_project_0cb3fd_idx',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='map_revision',
            new_name='mapset_revision',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='project',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='mapping',
        ),
        migrations.AddField(
            model_name='mappingsetmapping',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappingssetmappings', to='kernel.Mapping'),
        ),
        migrations.AddField(
            model_name='mappingsetmapping',
            name='mappingset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappingssetmappings', to='kernel.MappingSet'),
        ),
        migrations.AddField(
            model_name='mappingset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappingsets', to='kernel.Project'),
        ),
        migrations.AddField(
            model_name='submission',
            name='mappingset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kernel.MappingSet'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='mappingsetmapping',
            index=models.Index(fields=['mappingset', '-modified'], name='kernel_mapp_mapping_aa0fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='mappingsetmapping',
            index=models.Index(fields=['-modified'], name='kernel_mapp_modifie_adb447_idx'),
        ),
        migrations.AddIndex(
            model_name='mappingset',
            index=models.Index(fields=['project', '-modified'], name='kernel_mapp_project_73242f_idx'),
        ),
        migrations.AddIndex(
            model_name='mappingset',
            index=models.Index(fields=['-modified'], name='kernel_mapp_modifie_46a12a_idx'),
        ),
    ]
