# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0016_auto_20180823_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionMapping',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('revision', models.TextField(default='1')),
                ('map_revision', models.TextField(default='1')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissionmappings', to='kernel.Mapping')),
            ],
            options={
                'ordering': ['submission__id', '-modified'],
                'default_related_name': 'submissionmappings',
            },
        ),
        migrations.RemoveField(
            model_name='mappingset',
            name='mappings',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='mapset_revision',
        ),
        migrations.AlterField(
            model_name='mappingsetmapping',
            name='name',
            field=models.CharField(default='None - None', max_length=105, unique=True),
        ),
        migrations.AddField(
            model_name='submissionmapping',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissionmappings', to='kernel.Submission'),
        ),
        migrations.AddIndex(
            model_name='submissionmapping',
            index=models.Index(fields=['submission', '-modified'], name='kernel_subm_submiss_3ce3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionmapping',
            index=models.Index(fields=['-modified'], name='kernel_subm_modifie_ebcf5e_idx'),
        ),
    ]
