# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0017_mappingset_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='family',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='type',
            field=models.CharField(max_length=50, default='org.ehealthafrica.aether'),
        ),
    ]
