# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 16:16
from __future__ import unicode_literals

import aether.kernel.api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0018_schema_family'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['submission__id', 'name'], 'verbose_name': 'attachment', 'verbose_name_plural': 'attachments'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['project__id', '-modified'], 'verbose_name': 'entity', 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='mapping',
            options={'ordering': ['project__id', '-modified'], 'verbose_name': 'mapping', 'verbose_name_plural': 'mappings'},
        ),
        migrations.AlterModelOptions(
            name='mappingset',
            options={'ordering': ['project__id', '-modified'], 'verbose_name': 'mapping set', 'verbose_name_plural': 'mapping sets'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-modified'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='projectschema',
            options={'ordering': ['project__id', '-modified'], 'verbose_name': 'project schema', 'verbose_name_plural': 'project schemas'},
        ),
        migrations.AlterModelOptions(
            name='schema',
            options={'ordering': ['-modified'], 'verbose_name': 'schema', 'verbose_name_plural': 'schemas'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['project__id', '-modified'], 'verbose_name': 'submission', 'verbose_name_plural': 'submissions'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_file',
            field=models.FileField(upload_to=aether.kernel.api.models.__attachment_path__, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='md5sum',
            field=models.CharField(blank=True, max_length=36, verbose_name='file MD5'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='filename'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='kernel.Submission', verbose_name='submission'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='submission_revision',
            field=models.TextField(verbose_name='submission revision'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.Mapping', verbose_name='mapping'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='mapping_revision',
            field=models.TextField(verbose_name='mapping revision'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='modified',
            field=models.CharField(editable=False, max_length=100, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='payload'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='projectschema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.ProjectSchema', verbose_name='project schema'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='revision',
            field=models.TextField(default='1', verbose_name='revision'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Publishable', 'Publishable')], max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.Submission', verbose_name='submission'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='definition',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='mapping rules'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active?'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='is_read_only',
            field=models.BooleanField(default=False, verbose_name='read only?'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='mappingset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='kernel.MappingSet', verbose_name='mapping set'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='kernel.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='projectschemas',
            field=models.ManyToManyField(blank=True, editable=False, related_name='mappings', to='kernel.ProjectSchema', verbose_name='project schemas'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='revision',
            field=models.TextField(default='1', verbose_name='revision'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='input',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='input sample'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappingsets', to='kernel.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='revision',
            field=models.TextField(default='1', verbose_name='revision'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='AVRO schema'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='jsonld_context',
            field=models.TextField(blank=True, null=True, verbose_name='JSON LD context', help_text='JSON for Linking Data  https://json-ld.org/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rdf_definition',
            field=models.TextField(blank=True, null=True, verbose_name='RDF definition', help_text='Resource Description Framework  https://www.w3.org/TR/rdf-schema/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='revision',
            field=models.TextField(default='1', verbose_name='revision'),
        ),
        migrations.AlterField(
            model_name='project',
            name='salad_schema',
            field=models.TextField(blank=True, null=True, verbose_name='salad schema', help_text='Semantic Annotations for Linked Avro Data (SALAD)  https://www.commonwl.org/draft-3/SchemaSalad.html')
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='is_encrypted',
            field=models.BooleanField(default=False, verbose_name='encrypted?'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='mandatory_fields',
            field=models.TextField(blank=True, null=True, verbose_name='mandatory fields'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='masked_fields',
            field=models.TextField(blank=True, null=True, verbose_name='masked fields'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectschemas', to='kernel.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectschemas', to='kernel.Schema', verbose_name='schema'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='transport_rule',
            field=models.TextField(blank=True, null=True, verbose_name='transport rule'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='definition',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='AVRO schema'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='family',
            field=models.TextField(blank=True, null=True, verbose_name='schema family'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='revision',
            field=models.TextField(default='1', verbose_name='revision'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='type',
            field=models.CharField(default='org.ehealthafrica.aether', max_length=50, verbose_name='schema type'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='mappingset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kernel.MappingSet', verbose_name='mapping set'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='payload'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kernel.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='revision',
            field=models.TextField(default='1', verbose_name='revision'),
        ),
    ]
