# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0019_auto_20180827_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingsetmapping',
            name='name',
            field=models.CharField(max_length=105, unique=True),
        ),
    ]
