# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_entities(apps, schema_editor):
    Entity = apps.get_model('kernel', 'Entity')

    for entity in Entity.objects.all():
        entity.save()  # this will set the schema value


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0019_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='kernel.Schema', verbose_name='schema'),
        ),

        migrations.AlterField(
            model_name='entity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='kernel.Project', verbose_name='project'),
        ),

        migrations.RunPython(migrate_entities, migrations.RunPython.noop),
    ]
