# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 07:11
from __future__ import unicode_literals

import aether.python.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0020_entity_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='mapping_revision',
            field=models.TextField(blank=True, null=True, verbose_name='mapping revision'),
        ),

        # include field validators
        migrations.AlterField(
            model_name='mapping',
            name='definition',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[aether.python.validators.validate_mapping_definition], verbose_name='mapping rules'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[aether.python.validators.validate_avro_schema], verbose_name='AVRO schema'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='definition',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[aether.python.validators.validate_schema_definition], verbose_name='AVRO schema'),
        ),
    ]
