# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0020_auto_20180827_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mappingsetmapping',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappingsetmappings', to='kernel.Mapping'),
        ),
        migrations.AlterField(
            model_name='mappingsetmapping',
            name='mappingset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappingsetmappings', to='kernel.MappingSet'),
        ),
        migrations.AlterField(
            model_name='mappingsetmapping',
            name='name',
            field=models.CharField(blank=True, max_length=105, unique=True),
        ),
    ]
