# Generated by Django 2.1.7 on 2019-03-07 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0022_entity_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'default_related_name': 'attachments', 'ordering': ['submission__id', 'name'], 'verbose_name': 'attachment', 'verbose_name_plural': 'attachments'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'default_related_name': 'entities', 'ordering': ['project__id', '-modified'], 'verbose_name': 'entity', 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='mapping',
            options={'default_related_name': 'mappings', 'ordering': ['project__id', '-modified'], 'verbose_name': 'mapping', 'verbose_name_plural': 'mappings'},
        ),
        migrations.AlterModelOptions(
            name='mappingset',
            options={'default_related_name': 'mappingsets', 'ordering': ['project__id', '-modified'], 'verbose_name': 'mapping set', 'verbose_name_plural': 'mapping sets'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'default_related_name': 'projects', 'ordering': ['-modified'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='projectschema',
            options={'default_related_name': 'projectschemas', 'ordering': ['project__id', '-modified'], 'verbose_name': 'project schema', 'verbose_name_plural': 'project schemas'},
        ),
        migrations.AlterModelOptions(
            name='schema',
            options={'default_related_name': 'schemas', 'ordering': ['-modified'], 'verbose_name': 'schema', 'verbose_name_plural': 'schemas'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'default_related_name': 'submissions', 'ordering': ['project__id', '-modified'], 'verbose_name': 'submission', 'verbose_name_plural': 'submissions'},
        ),
        migrations.AlterField(
            model_name='entity',
            name='projectschema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='kernel.ProjectSchema', verbose_name='project schema'),
        ),
    ]
