# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0022_auto_20180828_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionmapping',
            name='mapping',
        ),
        migrations.RemoveField(
            model_name='submissionmapping',
            name='submission',
        ),
        migrations.AddField(
            model_name='mapping',
            name='is_read_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mappingset',
            name='mappings',
            field=models.ManyToManyField(blank=True, related_name='mappingsets', to='kernel.Mapping'),
        ),
        migrations.DeleteModel(
            name='SubmissionMapping',
        ),
    ]
