# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 11:45
from __future__ import unicode_literals

import aether.kernel.api.models
import aether.kernel.api.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    replaces = [
        ('kernel', '0001_initial'),
        ('kernel', '0002_auto_20171218_0854'),
        ('kernel', '0003_auto_20180112_0938'),
        ('kernel', '0004_submission_mapping_not_null'),
        ('kernel', '0005_auto_20180116_1246'),
        ('kernel', '0006_auto_20180122_1346'),
        ('kernel', '0007_auto_20180208_0928'),
        ('kernel', '0008_auto_20180208_0933'),
        ('kernel', '0009_auto_20180220_1058'),
        ('kernel', '0010_auto_20180305_1540'),
        ('kernel', '0011_auto_20180524_1303'),
        ('kernel', '0012_auto_20180524_1553'),
        ('kernel', '0013_auto_20180530_1411'),
        ('kernel', '0014_remove_submission_date'),
        ('kernel', '0015_auto_20180725_1310'),
        ('kernel', '0016_auto_20180907_1214'),
        ('kernel', '0017_mappingset_schema'),
        ('kernel', '0018_schema_family'),
        ('kernel', '0019_verbose_name'),
        ('kernel', '0020_entity_schema'),
        ('kernel', '0021_auto_20181023_0711'),
        ('kernel', '0022_entity_created'),
    ]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.TextField(default='1')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Publishable', 'Publishable')], max_length=20)),
                ('modified', models.CharField(editable=False, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField()),
                ('revision', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.TextField()),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('salad_schema', models.TextField()),
                ('jsonld_context', models.TextField()),
                ('rdf_definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('mandatory_fields', models.CharField(max_length=100)),
                ('transport_rule', models.TextField()),
                ('masked_fields', models.TextField()),
                ('is_encrypted', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectschemas', to='kernel.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('revision', models.TextField(default='1')),
                ('map_revision', models.TextField(default='1')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kernel.Mapping')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'ordering': ('-modified',),
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField()),
                ('revision', models.TextField(default='1')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.AddField(
            model_name='projectschema',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectschemas', to='kernel.Schema'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='kernel.Project'),
        ),
        migrations.AddField(
            model_name='entity',
            name='projectschema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.ProjectSchema'),
        ),
        migrations.AddField(
            model_name='entity',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.Submission'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('submission_revision', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('attachment_file', models.FileField(upload_to=aether.kernel.api.models.__attachment_path__)),
                ('md5sum', models.CharField(blank=True, max_length=36)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='kernel.Submission')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'ordering': ['submission__id', 'name'],
                'default_related_name': 'attachments',
            },
        ),
        migrations.AlterModelOptions(
            name='mapping',
            options={'ordering': ['name', 'revision']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name', 'revision']},
        ),
        migrations.AddField(
            model_name='mapping',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='project',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='projectschema',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='projectschema',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ('modified',), 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='mapping',
            options={'ordering': ('modified',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('modified',)},
        ),
        migrations.AlterModelOptions(
            name='projectschema',
            options={'ordering': ('modified',)},
        ),
        migrations.AlterField(
            model_name='mapping',
            name='revision',
            field=models.TextField(default='1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='jsonld_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rdf_definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='revision',
            field=models.TextField(default='1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='salad_schema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='mandatory_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='masked_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='transport_rule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ('-modified',), 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='mapping',
            options={'ordering': ['project__id', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='projectschema',
            options={'ordering': ['project__id', '-modified']},
        ),
        migrations.AddField(
            model_name='entity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.Project'),
        ),
        migrations.AddField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kernel.Project'),
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['project__id', '-modified'], 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['project__id', '-modified']},
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['submission', 'name'], name='kernel_atta_submiss_58224b_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['project', '-modified'], name='kernel_enti_project_5d5f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['-modified'], name='kernel_enti_modifie_c49ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['project', '-modified'], name='kernel_mapp_project_0cb3fd_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['-modified'], name='kernel_mapp_modifie_8c7640_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-modified'], name='kernel_proj_modifie_02889d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectschema',
            index=models.Index(fields=['project', '-modified'], name='kernel_proj_project_2dfa87_idx'),
        ),
        migrations.AddIndex(
            model_name='projectschema',
            index=models.Index(fields=['-modified'], name='kernel_proj_modifie_3ecab4_idx'),
        ),
        migrations.AddIndex(
            model_name='schema',
            index=models.Index(fields=['-modified'], name='kernel_sche_modifie_fc1ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['project', '-modified'], name='kernel_subm_project_3c72d6_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-modified'], name='kernel_subm_modifie_a4d81e_idx'),
        ),
        migrations.RunSQL(
            sql='\n            UPDATE kernel_submission S\n               SET project_id = M.project_id\n              FROM kernel_mapping M\n             WHERE S.mapping_id = M.id\n            ;\n\n            UPDATE kernel_entity E\n               SET project_id = S.project_id\n              FROM kernel_submission S\n             WHERE E.submission_id = S.id\n            ;\n\n            UPDATE kernel_entity E\n               SET project_id = PS.project_id\n              FROM kernel_projectschema PS\n             WHERE E.projectschema_id = PS.id\n               AND E.project_id IS NULL\n            ;\n            ',
            reverse_sql='',
        ),
        migrations.CreateModel(
            name='MappingSet',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('revision', models.TextField(default='1')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('input', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappingsets', to='kernel.Project')),
            ],
            options={
                'ordering': ['project__id', '-modified'],
                'default_related_name': 'mappingsets',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.Mapping'),
        ),
        migrations.AddField(
            model_name='entity',
            name='mapping_revision',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='is_read_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mapping',
            name='projectschemas',
            field=models.ManyToManyField(blank=True, editable=False, related_name='mappings', to='kernel.ProjectSchema'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='mappingset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='kernel.MappingSet'),
        ),
        migrations.AddField(
            model_name='submission',
            name='mappingset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kernel.MappingSet'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='kernel.Project'),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='map_revision',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='mapping',
        ),
        migrations.AddIndex(
            model_name='mappingset',
            index=models.Index(fields=['project', '-modified'], name='kernel_mapp_project_73242f_idx'),
        ),
        migrations.AddIndex(
            model_name='mappingset',
            index=models.Index(fields=['-modified'], name='kernel_mapp_modifie_46a12a_idx'),
        ),
        migrations.AddField(
            model_name='mappingset',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='family',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='type',
            field=models.CharField(default='org.ehealthafrica.aether', max_length=50),
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['submission__id', 'name'], 'verbose_name': 'attachment', 'verbose_name_plural': 'attachments'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['project__id', '-modified'], 'verbose_name': 'entity', 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='mapping',
            options={'ordering': ['project__id', '-modified'], 'verbose_name': 'mapping', 'verbose_name_plural': 'mappings'},
        ),
        migrations.AlterModelOptions(
            name='mappingset',
            options={'ordering': ['project__id', '-modified'], 'verbose_name': 'mapping set', 'verbose_name_plural': 'mapping sets'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-modified'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='projectschema',
            options={'ordering': ['project__id', '-modified'], 'verbose_name': 'project schema', 'verbose_name_plural': 'project schemas'},
        ),
        migrations.AlterModelOptions(
            name='schema',
            options={'ordering': ['-modified'], 'verbose_name': 'schema', 'verbose_name_plural': 'schemas'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['project__id', '-modified'], 'verbose_name': 'submission', 'verbose_name_plural': 'submissions'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_file',
            field=models.FileField(upload_to=aether.kernel.api.models.__attachment_path__, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='md5sum',
            field=models.CharField(blank=True, max_length=36, verbose_name='file MD5'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='filename'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='kernel.Submission', verbose_name='submission'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='submission_revision',
            field=models.TextField(verbose_name='submission revision'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.Mapping', verbose_name='mapping'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='mapping_revision',
            field=models.TextField(verbose_name='mapping revision'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='modified',
            field=models.CharField(editable=False, max_length=100, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='payload'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='projectschema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.ProjectSchema', verbose_name='project schema'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='revision',
            field=models.TextField(default='1', verbose_name='revision'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Publishable', 'Publishable')], max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='kernel.Submission', verbose_name='submission'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='definition',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='mapping rules'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active?'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='is_read_only',
            field=models.BooleanField(default=False, verbose_name='read only?'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='mappingset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='kernel.MappingSet', verbose_name='mapping set'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='kernel.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='projectschemas',
            field=models.ManyToManyField(blank=True, editable=False, related_name='mappings', to='kernel.ProjectSchema', verbose_name='project schemas'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='revision',
            field=models.TextField(default='1', verbose_name='revision'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='input',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='input sample'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappingsets', to='kernel.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='revision',
            field=models.TextField(default='1', verbose_name='revision'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='AVRO schema'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='jsonld_context',
            field=models.TextField(blank=True, help_text='JSON for Linking Data  https://json-ld.org/', null=True, verbose_name='JSON LD context'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rdf_definition',
            field=models.TextField(blank=True, help_text='Resource Description Framework  https://www.w3.org/TR/rdf-schema/', null=True, verbose_name='RDF definition'),
        ),
        migrations.AlterField(
            model_name='project',
            name='revision',
            field=models.TextField(default='1', verbose_name='revision'),
        ),
        migrations.AlterField(
            model_name='project',
            name='salad_schema',
            field=models.TextField(blank=True, help_text='Semantic Annotations for Linked Avro Data (SALAD)  https://www.commonwl.org/draft-3/SchemaSalad.html', null=True, verbose_name='salad schema'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='is_encrypted',
            field=models.BooleanField(default=False, verbose_name='encrypted?'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='mandatory_fields',
            field=models.TextField(blank=True, null=True, verbose_name='mandatory fields'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='masked_fields',
            field=models.TextField(blank=True, null=True, verbose_name='masked fields'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectschemas', to='kernel.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectschemas', to='kernel.Schema', verbose_name='schema'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='transport_rule',
            field=models.TextField(blank=True, null=True, verbose_name='transport rule'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='definition',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='AVRO schema'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='family',
            field=models.TextField(blank=True, null=True, verbose_name='schema family'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='revision',
            field=models.TextField(default='1', verbose_name='revision'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='type',
            field=models.CharField(default='org.ehealthafrica.aether', max_length=50, verbose_name='schema type'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='mappingset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kernel.MappingSet', verbose_name='mapping set'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='payload'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kernel.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='revision',
            field=models.TextField(default='1', verbose_name='revision'),
        ),
        migrations.AddField(
            model_name='entity',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='kernel.Schema', verbose_name='schema'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='kernel.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='mapping_revision',
            field=models.TextField(blank=True, null=True, verbose_name='mapping revision'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='definition',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[aether.kernel.api.validators.validate_mapping_definition], verbose_name='mapping rules'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[aether.kernel.api.validators.validate_avro_schema], verbose_name='AVRO schema'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='definition',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[aether.kernel.api.validators.validate_schema_definition], verbose_name='AVRO schema'),
        ),
        migrations.AddField(
            model_name='entity',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
    ]
