# Generated by Django 2.1.7 on 2019-03-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0100_initial_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.TextField(verbose_name='filename'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='projectschema',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.TextField(unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='type',
            field=models.TextField(default='org.ehealthafrica.aether', verbose_name='schema type'),
        ),
    ]
