# Generated by Django 2.1.8 on 2019-04-05 07:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0101_name_not_unique'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectSchema',
            new_name='SchemaDecorator',
        ),
        migrations.AlterModelOptions(
            name='SchemaDecorator',
            options={
                'verbose_name': 'schema decorator',
                'verbose_name_plural': 'schema decorators',
                'ordering': ['project__id', '-modified'],
                'default_related_name': 'schemadecorators',
            },
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='projectschema',
            new_name='schemadecorator',
        ),
        migrations.RenameField(
            model_name='mapping',
            old_name='projectschemas',
            new_name='schemadecorators',
        ),
        migrations.AddIndex(
            model_name='schemadecorator',
            index=models.Index(fields=['project', '-modified'], name='kernel_sche_project_49476e_idx'),
        ),
        migrations.AddIndex(
            model_name='schemadecorator',
            index=models.Index(fields=['-modified'], name='kernel_sche_modifie_7a154a_idx'),
        ),
    ]
