# Generated by Django 2.1.8 on 2019-04-05 07:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0101_name_not_unique'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectSchema',
            new_name='SchemaDecorator',
        ),
        migrations.AlterModelOptions(
            name='SchemaDecorator',
            options={
                'verbose_name': 'schema decorator',
                'verbose_name_plural': 'schema decorators',
                'ordering': ['project__id', '-modified'],
                'default_related_name': 'schemadecorators',
            },
        ),
        migrations.RemoveIndex(
            model_name='schemadecorator',
            name='kernel_proj_project_2dfa87_idx',
        ),
        migrations.RemoveIndex(
            model_name='schemadecorator',
            name='kernel_proj_modifie_3ecab4_idx',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='projectschema',
            new_name='schemadecorator',
        ),
        migrations.RenameField(
            model_name='mapping',
            old_name='projectschemas',
            new_name='schemadecorators',
        ),
        migrations.AlterField(
            model_name='mapping',
            name='schemadecorators',
            field=models.ManyToManyField(blank=True, editable=False, related_name='mappings', to='kernel.SchemaDecorator', verbose_name='schema decorators'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='schemadecorator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='kernel.SchemaDecorator', verbose_name='schema decorator'),
        ),
        migrations.AlterField(
            model_name='schemadecorator',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemadecorators', to='kernel.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='schemadecorator',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemadecorators', to='kernel.Schema', verbose_name='schema'),
        ),
        migrations.AddIndex(
            model_name='schemadecorator',
            index=models.Index(fields=['project', '-modified'], name='kernel_sche_project_49476e_idx'),
        ),
        migrations.AddIndex(
            model_name='schemadecorator',
            index=models.Index(fields=['-modified'], name='kernel_sche_modifie_7a154a_idx'),
        ),
    ]
