# Generated by Django 2.2.1 on 2019-05-09 10:06

from django.db import migrations, models
import django.db.models.deletion


def migrate__update_submissions(apps, schema_editor):
    Submissions = apps.get_model('kernel', 'Submission')
    for submission in Submissions.objects.all():
        submission.save() # ensures project from mappingset is linked to submission

class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0102_schema_decorator'),
    ]

    operations = [
        migrations.RunPython(
            code=migrate__update_submissions,
            reverse_code=migrations.RunPython.noop,
            # The optional elidable argument determines whether or not the operation
            # will be removed (elided) when squashing migrations.
            elidable=True,
        ),
        migrations.AlterField(
            model_name='submission',
            name='mappingset',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='submissions',
                to='kernel.MappingSet',
                verbose_name='mapping set'
            ),
        ),
        migrations.AlterField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='submissions',
                to='kernel.Project',
                verbose_name='project'
            ),
        ),
    ]
