# Generated by Django 2.2.1 on 2019-05-15 09:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations

def migrate__update_schemadecorator(apps, schema_editor):
    SchemaDecorator = apps.get_model('kernel', 'SchemaDecorator')
    for sd in SchemaDecorator.objects.all():
        sd.save() # default topic_name to { name: [schemadecorator.name] }

class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0103_submission_no_cascade_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemadecorator',
            name='topic',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='topic'),
        ),
        migrations.RunPython(
            code=migrate__update_schemadecorator,
            reverse_code=migrations.RunPython.noop,
            # The optional elidable argument determines whether or not the operation
            # will be removed (elided) when squashing migrations.
            elidable=True,
        ),
    ]
