# Generated by Django 2.2.4 on 2019-09-03 08:30

import aether.kernel.api.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0104_schemadecorator_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='definition',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                validators=[aether.kernel.api.validators.wrapper_validate_schema_definition],
                verbose_name='AVRO schema'
            ),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='definition',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                validators=[aether.kernel.api.validators.wrapper_validate_mapping_definition],
                verbose_name='mapping rules'
            ),
        ),
    ]
