# Generated by Django 2.2.3 on 2019-07-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0104_schemadecorator_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_extracted',
            field=models.BooleanField(default=False, verbose_name='entity extracted?'),
        ),
    ]
