# Generated by Django 2.2.7 on 2019-11-26 12:47

import aether.kernel.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0106_project_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_file',
            field=models.FileField(max_length=500, upload_to=aether.kernel.api.models.__attachment_path__, verbose_name='file'),
        ),
    ]
