# Generated by Django 2.2.9 on 2020-01-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0107_attachment_file_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_extracted',
            field=models.BooleanField(default=False, verbose_name='entity extracted?'),
        ),
    ]
