# Generated by Django 2.2.9 on 2020-01-09 16:53

from django.db import migrations, models


def migrate__update_submissions(apps, schema_editor):
    Submissions = apps.get_model('kernel', 'Submission')
    for submission in Submissions.objects.all():
        submission.is_extracted = submission.entities.count() > 0
        submission.save(update_fields=['is_extracted'])


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0107_attachment_file_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_extracted',
            field=models.BooleanField(default=False, verbose_name='entities extracted?'),
        ),
        migrations.RunPython(
            code=migrate__update_submissions,
            reverse_code=migrations.RunPython.noop,
            # The optional elidable argument determines whether or not the operation
            # will be removed (elided) when squashing migrations.
            elidable=True,
        ),
    ]
