# Generated by Django 2.2.7 on 2019-11-27 10:28

import aether.kernel.api.models
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kernel', '0107_attachment_file_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.TextField(default='1', verbose_name='revision')),
                ('name', models.TextField(verbose_name='name')),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False, verbose_name='settings')),
                ('status', models.CharField(default='INIT', editable=False, max_length=20, verbose_name='status')),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(editable=False, max_length=500, upload_to=aether.kernel.api.models.__task_path__, verbose_name='file'), blank=True, default=list, editable=False, null=True, size=None, verbose_name='generated files')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
                ('project', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kernel.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['project__id', '-modified'],
                'default_related_name': 'tasks',
            },
        ),
        migrations.AddIndex(
            model_name='exporttask',
            index=models.Index(fields=['project', '-modified'], name='kernel_expo_project_e19d66_idx'),
        ),
        migrations.AddIndex(
            model_name='exporttask',
            index=models.Index(fields=['-modified'], name='kernel_expo_modifie_9b8dbe_idx'),
        ),
    ]
