# Generated by Django 3.1 on 2020-08-11 08:58

import aether.kernel.api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0109_export_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='payload',
            field=models.JSONField(verbose_name='payload'),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='settings',
            field=models.JSONField(default=dict, editable=False, verbose_name='settings'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='definition',
            field=models.JSONField(validators=[aether.kernel.api.validators.wrapper_validate_mapping_definition], verbose_name='mapping rules'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='input',
            field=models.JSONField(blank=True, null=True, verbose_name='input sample'),
        ),
        migrations.AlterField(
            model_name='mappingset',
            name='schema',
            field=models.JSONField(blank=True, null=True, validators=[aether.kernel.api.validators.wrapper_validate_schema_input_definition], verbose_name='AVRO schema'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='definition',
            field=models.JSONField(validators=[aether.kernel.api.validators.wrapper_validate_schema_definition], verbose_name='AVRO schema'),
        ),
        migrations.AlterField(
            model_name='schemadecorator',
            name='topic',
            field=models.JSONField(blank=True, null=True, verbose_name='topic'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='payload',
            field=models.JSONField(verbose_name='payload'),
        ),
    ]
