# Generated by Django 3.1.11 on 2021-05-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0110_json_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='jsonld_context',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rdf_definition',
        ),
        migrations.RemoveField(
            model_name='project',
            name='salad_schema',
        ),
    ]
