apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  odk-database-user: cG9zdGdyZXM=
  odk-database-password: ""
  odk-database-name: WVdWMGFHVnk=
  odk-django-secret-key: c2VjcmV0
  odk-token: YTJkNmJjMjBhZDE2ZWM4ZTcxNWYyZjQyZjU0ZWIwMGNiYmVhMmQyNA==
  kernel-token: YTJkNmJjMjBhZDE2ZWM4ZTcxNWYyZjQyZjU0ZWIwMGNiYmVhMmQyNA==
