# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 12:01
from __future__ import unicode_literals

import aether.odk.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xform',
            name='xml_data',
            field=models.TextField(blank=True, validators=[aether.odk.api.models.validate_xmldict]),
        ),
    ]
