# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odk', '0007_xform_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='xform',
            name='surveyors',
            field=models.ManyToManyField(blank=True, related_name='xforms', to=settings.AUTH_USER_MODEL),
        ),
    ]
