# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_survey_from_xforms(apps, schema_editor):
    xForm = apps.get_model('odk', 'xform')
    Survey = apps.get_model('odk', 'survey')

    # iterate all xForms
    for xform in xForm.objects.all():
        survey, _ = Survey.objects.get_or_create(
            survey_id=xform.aether_core_survey_id,
        )
        # copy surveyors
        for surveyor in xform.surveyors.all():
            survey.surveyors.add(surveyor)
        survey.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odk', '0008_xform_surveyors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.IntegerField(primary_key=True)),
                ('name', models.TextField(null=True, blank=True, default='')),
                ('surveyors', models.ManyToManyField(blank=True, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
        ),

        # create surveys from xforms
        migrations.RunPython(create_survey_from_xforms),

        migrations.AlterField(
            model_name='xform',
            name='aether_core_survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xforms', to='odk.Survey'),
        ),
        migrations.RenameField(
            model_name='xform',
            old_name='aether_core_survey_id',
            new_name='survey',
        )
    ]
