# Generated by Django 2.0.1 on 2018-01-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.UUIDField()),
                ('project_name', models.TextField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
