# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 13:40
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xform',
            name='gather_core_url',
        ),
        migrations.AddField(
            model_name='xform',
            name='gather_core_survey_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xform',
            name='xml_data',
            field=models.TextField(blank=True, validators=[api.models.validate_xmldict]),
        ),
    ]
