# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 19:45
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xform',
            name='form_id',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='xform',
            name='xml_data',
            field=models.TextField(blank=True, validators=[api.models.validate_xmldict]),
        ),
    ]
