# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_xform_gather_core_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xform',
            name='gather_core_url',
            field=models.URLField(default=''),
        ),
    ]
