# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20170316_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xform',
            name='form_id',
        ),
    ]
