FROM python:3.6-slim-jessie

################################################################################
## setup container
################################################################################

RUN pip install --upgrade pip

################################################################################
## install app
## copy files one by one and split commands to use docker cache
################################################################################

WORKDIR /code
COPY ./ /code

################################################################################
## last setup steps
################################################################################

# create user to run container (avoid root user)
RUN useradd -u 2000 -ms /bin/false aether
RUN chown -R aether: /code

USER aether

ENTRYPOINT ["/code/entrypoint.sh"]
