FROM python:3.6-slim-jessie

################################################################################
## setup container
################################################################################

RUN pip install --upgrade pip

################################################################################
## install app
## copy files one by one and split commands to use docker cache
################################################################################

WORKDIR /code
COPY ./ /code

################################################################################
## copy application version and create git revision
################################################################################

ARG VERSION
RUN echo $VERSION > VERSION
ARG GIT_REVISION
RUN echo $GIT_REVISION > REVISION

################################################################################
## last setup steps
################################################################################

# create user to run container (avoid root user)
# set UID to travis' so PIP cache can be written to
RUN useradd -u 2000 -ms /bin/false aether
RUN chown -R aether: /code
# chown /usr/local so our user can get to their libs
RUN chown -R aether: /usr/local
USER 2000

ENTRYPOINT ["/code/entrypoint.sh"]
