FROM python:3.6-slim-jessie

# create user to run container (avoid root user)
# and do this before PIP installs so we can install at runtime.
RUN useradd -u 2000 -ms /bin/false aether
USER 2000:50

################################################################################
## setup container
################################################################################

RUN pip install --upgrade pip

################################################################################
## install app
## copy files one by one and split commands to use docker cache
################################################################################

WORKDIR /code
COPY ./ /code

################################################################################
## last setup steps
################################################################################

RUN chown -R aether: /code

ENTRYPOINT ["/code/entrypoint.sh"]
