version: "2.1"
services:
  example-consumer:
    build: ./example
    stdin_open: true
    tty: true
    environment:
     - PYTHONUNBUFFERED=1
    networks:
      - aether
    command: start

networks:
  aether:
    external:
      name: aether_internal
